server:
  port: 8080
spring:
  application.name: meeting-room-management
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory H2 database
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect